version: '3.8'
services:
  code-server:
    build: .
    container_name: code-server
    environment:
      - PASSWORD=yourpasswordhere
    volumes:
      - /Users/manaskulkarni/test:/home/coder/project
    working_dir: /home/coder/project
    ports:
      - "8080:8080"
    restart: unless-stopped
