version: '3.8'
services:
  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    environment:
      - PASSWORD=yourpasswordhere
    volumes:
      - ./:/home/coder/project
    working_dir: /home/coder/project
    ports:
      - "8080:8080"
    restart: unless-stopped
